# Site settings
title: Beom Woo Kang
description: Personal Website
# baseurl: "" # the subpath of your site, e.g. /blog
baseurl: ""
#url: https://beomwookang.github.io
url: "localhost:4000"

# User settings
username: Beom Woo Kang
user_description: Hi! I am a Masters Student in Computer Science at Hanyang University.
#user_description: Hi! I am an M.S. student in Computer Science at Hanyang University advised by <a href="https://sites.google.com/site/hyucasslab/home/professor?authuser=0">Yongjun Park</a>.
user_title: Researcher, Writer, Architect
email: beomwookang@gmail.com
github_username:  beomwookang

exclude: ['package.json', 'src' , 'node_modules']

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#
# Analytics
analytics:
  provider               : "google-gtag"  # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-6ZZ9WX70Q1"
    anonymize_ip         : # true, false (default)
